### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by anushkaa-02**
# Title 
Weather App

# Description
This is a weather application using React.

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have added my Synapse Ticket to the `README.md`
- [x] I have added screenshots  of my project to the `README.md`
- [x] Folder Name = Project Name.

### CODE REVIEW

**Review by Priyadarshan2000 — CHANGES_REQUESTED** [review]
@pilipi-puu-puu Next time You upload a single project in a single Pr. 

in the Weather App/src/components/Tempapp.js line no 25 comments on this line 
using 
{/* onChange is a event handler jeta input change ke check/search kore. */}

Screenshot 2023-01-11 at 10 52 49 PM

and your comment line is best 😂 
@pilipi-puu-puu  remember next time you upload a single project. 
I label hard because you upload 2 project

**Review by swastik-bose007 — APPROVED** [review]
Great work 🌟 but try to make single PR at a time : )

**Review by Priyadarshan2000 — APPROVED** [review]
image
Great work @pilipi-puu-puu 👍 keep contributing  🎉👨🏻‍💻

**Comment by anushkaa-02** [comment]
@Priyadarshan2000 Actually sometimes I forget the usage that's why🙂...I should remove those before uploading🥲

**Pull request merged**
