### PR TITLE
Evm dummy

### PR DESCRIPTION
**Pull request by Ankit62042**
# Evm Dummy
This is a dummy design of even using HTML and CSS 
# Description

Please include a summary of the change

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have added my Synapse Ticket to the `README.md`
- [x] I have added screenshots  of my project to the `README.md`
- [x] Folder Name = Project Name.

### CODE REVIEW

**Review by Priyadarshan2000 — CHANGES_REQUESTED** [review]
@Ankit62042 make this responsive

**Comment by Ankit62042** [comment]
Made it resopnsive and  also remove the form

**Comment by Ankit62042** [comment]
Screenshot (215)

**Review by swastik-bose007 — APPROVED** [review]
Calender color palate is really good but where is your code files? and also please wait for the approval of one PR then go for next....
EVM dummy is great but its UI, color and font could be better

**Review by Priyadarshan2000 — APPROVED** [review]
Great job. @Ankit62042 👍  keep contributing  🎉👨🏻‍💻

**Pull request merged**
