### PR TITLE
23-Pennies-COMMIT

### PR DESCRIPTION
**Pull request by dalalsoham**
# Title 
23 Pennies Game Website

# Description

This project is a 23 Pennies game Website only using HTML , CSS & JS. An amazing and interesting website for all game lovers and also my 2nd small game project.It is a device friendly website.

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have added my Synapse Ticket to the `README.md`
- [x] I have added screenshots  of my project to the `README.md`
- [x] Folder Name = Project Name.

### CODE REVIEW

**Review by CHIRANTAN-001 — CHANGES_REQUESTED** [review]
image

@dalalsoham  can you center your whole design? It'll be looking better.

**Comment by dalalsoham** [comment]
@CHIRANTAN-001 Changed the whole design and now it's in the center of the page.

**Review by swastik-bose007 — APPROVED** [review]

**Review by Priyadarshan2000 — APPROVED** [review]
Great Job @dalalsoham  👍 keep contributing 🎉

**Review by CHIRANTAN-001 — APPROVED** [review]
Great Job @dalalsoham

**Pull request merged**
