### PR TITLE
Adding a simple landing page  Eduhub  v0.1

### PR DESCRIPTION
**Pull request by Niladri2003**
# Title 
Please include the Title of Your Project

# Description

Please include a summary of the change

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have added my Synapse Ticket to the `README.md`
- [x] I have added screenshots  of my project to the `README.md`
- [x] Folder Name = Project Name.

### CODE REVIEW

**Comment by Niladri2003** [comment]
I made this project with tailwind css and html. 
This is a simple responsive landing page for online educational platforms.

**Review by Priyadarshan2000 — APPROVED** [review]
Great Job @Niladri2003  👍 keep contributing 🎉 UI is beautiful 🤩

**Review by CHIRANTAN-001 — CHANGES_REQUESTED** [review]
image
image

@Niladri2003  your project is great🎉. Please try to fix the above alignment problems .

**Review by CHIRANTAN-001 — CHANGES_REQUESTED** [review]
image
Fix this too for iPad view @Niladri2003

**Comment by Niladri2003** [comment]
Alignment problems solved both mobile and iPad view.
Please check it  sir.

**Review by CHIRANTAN-001 — APPROVED** [review]
Great job @Niladri2003. Keep Contributing🎊🎉

**Pull request merged**
