### PR TITLE
Analog Clock

### PR DESCRIPTION
**Pull request by Arnab2012**
# Title 
Analog Clock

# Description

It is an Analog Clock showing time, created using basic HTML, CSS and JS.
Website Link--> https://arnab2012.github.io/Analog-Clock/

## Checklist:

- [✔ ] My code follows the style guidelines(Clean Code) of this project
- [✔ ] I have performed a self-review of my own code
- [✔ ] I have commented my code, particularly in hard-to-understand areas
- [✔] I have created a helpful and easy to understand `README.md`
- [✔] I have added my Synapse Ticket to the `README.md`
- [✔] I have added screenshots  of my project to the `README.md`
- [✔ ] Folder Name = Project Name.

### CODE REVIEW

**Review by swastik-bose007 — APPROVED** [review]
@Arnab2012 great bro 🌟..... but why Devtown certificate is here : )

**Review by Priyadarshan2000 — CHANGES_REQUESTED** [review]
image

@Arnab2012  delete your Dev Town Certificate

**Comment by Arnab2012** [comment]
> @Arnab2012 great bro 🌟..... but why Devtown certificate is here : )

Sorry....actually I have mistakenly copied the file to the project folder and it was uploaded in the github repository too !!!

**Comment by Arnab2012** [comment]
> image
> 
> @Arnab2012 delete your Dev Town Certificate

I have deleted it. Please verify it .

**Review by Priyadarshan2000 — APPROVED** [review]
image
great job @Arnab2012 👍 keep contributing 👨🏻‍💻🎉

**Pull request merged**
