### PR TITLE
Simple Responsive Join us page

### PR DESCRIPTION
**Pull request by Niladri2003**
# Signup page 

# This is a simple HTML and CSS login page made with the help of tailwind css

Please include a summary of the change

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have added my Synapse Ticket to the `README.md`
- [x] I have added screenshots  of my project to the `README.md`
- [x] Folder Name = Project Name.

### CODE REVIEW

**Comment by Niladri2003** [comment]
Join us page Design overview
p-1
Desktop view
p-2
Mobile view

**Review by Priyadarshan2000 — CHANGES_REQUESTED** [review]
@Niladri2003  add your project title and project description

**Comment by Niladri2003** [comment]
All requested changes have been done.
Please check it .

**Review by Priyadarshan2000 — APPROVED** [review]
great work @Niladri2003  👍 keep contributing  👨🏻‍💻🎉

**Pull request merged**
