### PR TITLE
Tic-Tac-Toe

### PR DESCRIPTION
**Pull request by Arnab2012**
# Title 
Please include the Title of Your Project

# Description

Please include a summary of the change

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have added my Synapse Ticket to the `README.md`
- [x] I have added screenshots  of my project to the `README.md`
- [x] Folder Name = Project Name.

### CODE REVIEW

**Comment by Arnab2012** [comment]
I have added my initial Project to Synapse 1.0 , and the project is a gaming website - Tic-Tac-Toe.

**Comment by swastik-bose007** [comment]
great work bro 🌟

**Review by swastik-bose007 — APPROVED** [review]
great work bro 🌟

**Review by Priyadarshan2000 — APPROVED** [review]
LGTM..Great Job 💯  @Arnab2012  👍 🎉

**Pull request merged**
