### PR TITLE
QUIZ

### PR DESCRIPTION
**Pull request by Ankit62042**
# Title 
QUIZ

# Description

This is a project where user give quiz and test there knowledge and check score.I used HTML,CSS and javascript to build this project

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have added my Synapse Ticket to the `README.md`
- [x] I have added screenshots  of my project to the `README.md`
- [x] Folder Name = Project Name.

### CODE REVIEW

**Review by CHIRANTAN-001 — CHANGES_REQUESTED** [review]
image

@Ankit62042  images are not visible. Try to allocate them properly.

**Review by CHIRANTAN-001 — CHANGES_REQUESTED** [review]
image

@Ankit62042  make this responsive

**Review by Priyadarshan2000 — CHANGES_REQUESTED** [review]
@Ankit62042 change the image path  in line no 14
Screenshot 2023-01-05 at 10 31 35 PM

**Comment by Priyadarshan2000** [comment]
@Ankit62042 updates?

**Comment by Ankit62042** [comment]
Chages updated
check

**Comment by Ankit62042** [comment]
> image
> 
> @Ankit62042 make this responsive

Screenshot (212)

**Review by CHIRANTAN-001 — APPROVED** [review]
Great Job @Ankit62042 🎉keep contributing🎊

**Pull request merged**
