### PR TITLE
Portfolio Website_Ankit_Kumar

### PR DESCRIPTION
**Pull request by Ankit62042**
# Title 

Portfolio Website_Ankit_Kumar
# Description

This a Portfolio website  created using HTML,CSS,JAVASCRIPT and Bootstrap include different section like Banner,Projects,education,experiences

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have added my Synapse Ticket to the `README.md`
- [x] I have added screenshots  of my project to the `README.md`
- [x] Folder Name = Project Name.

### CODE REVIEW

**Comment by Priyadarshan2000** [comment]
@Ankit62042  type x inside the [ ] don't "#" update this .

**Review by Priyadarshan2000 — CHANGES_REQUESTED** [review]
@Ankit62042 style the projects  section cards properly 
Screenshot 2023-01-02 at 1 22 24 PM
change the width and Height inside 
.card-body {
}

**Comment by Ankit62042** [comment]
okay

**Comment by Ankit62042** [comment]
Screenshot (207)


@Priyadarshan2000 chages the style of project section card

**Comment by Priyadarshan2000** [comment]
> Screenshot (207)
> 
> @Priyadarshan2000 chages the style of project section card

ok, @Ankit62042 commit these changes and don't add more than one project in a single PR.

**Review by CHIRANTAN-001 — APPROVED** [review]

**Review by CHIRANTAN-001 — COMMENTED** [review]
@Ankit62042  update your change

**Comment by CHIRANTAN-001** [comment]
image

@Ankit62042  push the updated code

**Comment by Ankit62042** [comment]
updated

**Review by Priyadarshan2000 — APPROVED** [review]

**Review by CHIRANTAN-001 — APPROVED** [review]

**Comment by Priyadarshan2000** [comment]
@Ankit62042 great job 👍

**Review by swastik-bose007 — COMMENTED** [review]
good work

**Pull request merged**
