### PR TITLE
Social Media Website with Theme Customization

### PR DESCRIPTION
**Pull request by anushkaa-02**
# Title 
Social Media Website with Theme Customization

# Description
- Default home page
- Notification
- Messages [Primary, General,request]
- Stories
- Post
- Analytics
- Settings
- Theme
  - Font size increase/decrease
  - Color [4 option]
  - Background [Light/Dim/Dark]

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have added my Synapse Ticket to the `README.md`
- [x] I have added screenshots  of my project to the `README.md`
- [x] Folder Name = Project Name.

### CODE REVIEW

**Review by swastik-bose007 — APPROVED** [review]
UI looks very fantastic🌟

**Review by CHIRANTAN-001 — APPROVED** [review]
The whole functionality and UI of the website is awesome @pilipi-puu-puu 🎉🎊🔥

**Comment by anushkaa-02** [comment]
@CHIRANTAN-001 kindly add the label.

**Comment by CHIRANTAN-001** [comment]
@pilipi-puu-puu label is added👍

**Pull request merged**
